src/main/java/gov/ca/cwds/rest/api/domain/DomainChef.java, src/test/java/gov/ca/cwds/rest/api/domain/DomainChefTest.java
Added an extra formatter to convert legacy DB dates
=> 146822823 add date formatting in domain chef

src/main/java/gov/ca/cwds/auth/User.java, src/main/java/gov/ca/cwds/auth/realms/JwtRealm.java, src/main/java/gov/ca/cwds/data/SharedSessionFactory.java, src/main/java/gov/ca/cwds/data/persistence/cms/Base62.java, src/main/java/gov/ca/cwds/logging/ApiLogUtils.java
Added the Logger and throw the exceptions, Changed the Exception to a Specific Exception and some naming convention.
=> SonarQube Bugs and Vulnerabilities Fix

src/main/java/gov/ca/cwds/rest/filters/ApiRequestCommonInfo.java
modified method incrementAndGetSequenceExternalTable() to make it public
=> made incrementsequence public

src/main/java/gov/ca/cwds/rest/api/domain/DomainChef.java, src/test/java/gov/ca/cwds/rest/api/domain/DomainChefTest.java
=> 146822823 Remove unneeded helper methods in domain chef

api-core-rest/src/main/java/gov/ca/cwds/rest/SwaggerConfiguration.java, api-core-rest/src/main/java/gov/ca/cwds/rest/views/SwaggerView.java, api-core-rest/src/main/resources/gov/ca/cwds/rest/views/swagger.mustache
Logout button was added to Swagger
**logoutUrl** configuration parameter is exposed to support logout functionality
=> 150896358 logout button to swagger

api-core-rest/src/main/java/gov/ca/cwds/rest/SwaggerConfiguration.java
=> #150896358 Perry: add logout button to Swagger

build.gradle
Update version of shiro-security
=> Update shiro-security version to 0.4.2_116-RC

build.gradle
=> Rollback version

api-core-rest/src/main/java/gov/ca/cwds/rest/validation/IfThenNot.java, api-core-rest/src/main/java/gov/ca/cwds/rest/validation/IfThenNotValidator.java
Rule - 00807
If REFERRAL. Application for Petition Ind = Y then REFERRAL. Referral Response Type <> Evaluated Out.
Based on the rule created an annotation to handle this implementation and will be placed over the referral domain.
=> Created generic annotation to handle the if Property and thenProperty.

api-core-rest/src/main/java/gov/ca/cwds/rest/validation/AfterDateValid.java, api-core-rest/src/main/java/gov/ca/cwds/rest/validation/AfterDateValidator.java, api-core-rest/src/test/java/gov/ca/cwds/rest/validation/AfterDateValidatorTest.java, api-core-rest/src/test/java/gov/ca/cwds/rest/validation/IfThenNotValidatorTest.java
R – 10664 REFERRAL.Limited_Access_Date must be >= (in focus) REFERRAL.Received_Date. 
For the above rule created the annotation to apply for the Referral to validate the received date and the limited access date. Limited access date should be greater than or equal to received date.
=> Created an annotation to validate the two dates

legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/dao/ChildClientDao.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/ChildClient.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/enums/Adoptable.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/enums/AdoptionStatus.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/enums/AssignmentRecipient.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/enums/AssignmentType.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/enums/AwolAbducted.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/enums/DateOfBirthStatus.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/enums/Disability.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/enums/Gender.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/enums/HispanicOrigin.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/enums/IcwaEligibility.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/enums/IncapacitatedParentStatus.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/enums/LimitedAccess.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/enums/LiterateStatus.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/enums/MilitaryStatus.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/enums/ParentUnemployedStatus.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/enums/PreviouslyAdopted.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/enums/ResponsibleAgency.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/enums/Sensitivity.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/enums/Soc158placementsStatus.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/enums/UnableToDetermineReason.java
=> - add from code methods into enums

legacy-data-access-services/src/test/java/gov/ca/cwds/cms/data/access/service/impl/R00741Test.java
=> Tpt3 92 client rule

legacy-data-access-services/src/main/resources/placement-home-legacy-rules/R-00179.drl, legacy-data-access-services/src/main/resources/placement-home-legacy-rules/R-00180.drl, legacy-data-access-services/src/test/java/gov/ca/cwds/cms/data/access/service/impl/placementHome/R00179Test.java, legacy-data-access-services/src/test/java/gov/ca/cwds/cms/data/access/service/impl/placementHome/R00180Test.java
fix for  https://osi-cwds.atlassian.net/browse/CALS-5200
=> fix R-00179 R-00180

build.gradle
https://osi-cwds.atlassian.net/browse/CALS-5461
=> Placement Home: implement changes introduced by CWS/CMS 8.1 update

api-core-cms/src/main/java/gov/ca/cwds/data/persistence/cms/CmsKeyIdGenerator.java
Added back the generate method. It will resolve all the service class and the test cases.
=> Fix for the Ferb API Project with CmsKeyGenrator

api-core-cms/src/main/java/gov/ca/cwds/data/es/ElasticSearchPerson.java, api-core-cms/src/main/resources/elasticsearch/mapping/map_person_5x_snake.json, api-core-cms/src/main/resources/elasticsearch/mapping/map_person_summary.json, api-core-cms/src/test/java/gov/ca/cwds/data/es/ElasticSearchPersonTest.java
Added "client_counties" to index mappings. Made the "client_county" deprecated for backward compatibility but eventually it will be removed.
=> Added client counties

legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/BaseStaffPerson.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/PlacementEpisode.java
=> CALS API: Impossible to fetch children for facility Ady1UyD01w in INT

api-core-abac/src/main/java/gov/ca/cwds/authorizer/AbstractBaseAuthorizer.java, api-core-abac/src/main/java/gov/ca/cwds/authorizer/ClientAbstractReadAuthorizer.java, api-core-abac/src/main/java/gov/ca/cwds/authorizer/ClientBaseReadAuthorizer.java, api-core-abac/src/main/java/gov/ca/cwds/authorizer/ClientResultReadAuthorizer.java, api-core-abac/src/main/java/gov/ca/cwds/authorizer/drools/configuration/ClientResultAuthorizationDroolsConfiguration.java, api-core-abac/src/main/java/gov/ca/cwds/authorizer/util/StaffPrivilegeUtil.java, api-core-abac/src/main/resources/client-authorization-rules/client-authorization.drl, api-core-abac/src/main/resources/client-authorization-rules/kmodule.xml, api-core-abac/src/main/resources/client-result-authorization-rules/auto-discovery, api-core-abac/src/main/resources/client-result-authorization-rules/client-result-authorization.drl, api-core-abac/src/main/resources/client-result-authorization-rules/kmodule.xml, api-core-abac/src/test/java/gov/ca/cwds/authorizer/ClientResultReadAuthorizerTest.java, legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/service/impl/ClientCoreService.java
User Story: https://osi-cwds.atlassian.net/browse/CALS-5654
Description: added additional Authorizer to implement Client Result authorization rules from IBM Security Gude
=> CALS-5654:  Client result authorizer added

api-core-test-support/src/main/java/gov/ca/cwds/rest/authenticate/CWDSAuthenticationClient.java, api-core-test-support/src/main/java/gov/ca/cwds/rest/authenticate/CWDSAuthenticationClientConfig.java
Removed the password from constant and cleaned up client moving it into small methods.
=> Refactoring and Vulnerabilities Fix

.github/PULL_REQUEST_TEMPLATE.md, api-core-abac/src/main/java/gov/ca/cwds/authorizer/AbstractBaseAuthorizer.java, api-core-abac/src/main/java/gov/ca/cwds/authorizer/ClientAbstractReadAuthorizer.java, api-core-abac/src/main/java/gov/ca/cwds/authorizer/ClientResultReadAuthorizer.java, api-core-abac/src/test/java/gov/ca/cwds/authorizer/ClientAbstractReadAuthorizerTest.java, api-core-abac/src/test/java/gov/ca/cwds/authorizer/ClientResultReadAuthorizerTest.java, build.gradle, legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/service/impl/ClientCoreService.java
User Story: https://osi-cwds.atlassian.net/browse/CALS-5654
Description: fixed error related to DroolsConfiguration injection in Client Authorizers
=> CALS-5654: fix Client authorizers 

build.gradle
- [CALS-5654: Enforce IBM Security Guide requirements regarding Client Search in Get Facility Children API in CALS API](https://osi-cwds.atlassian.net/browse/CALS-5654)
Api Security version updated. In new version added toString method on PerryAccount class so that it can be printed in logs
N/A
N/A
=> CALS-5654: Api Security version update

legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/dto/ClientEntityAwareDTO.java, legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/service/impl/ClientCoreService.java, legacy-data-access-services/src/main/resources/client-legacy-rules/R-00756.drl, legacy-data-access-services/src/main/resources/client-legacy-rules/auto-discovery, legacy-data-access-services/src/test/java/gov/ca/cwds/cms/data/access/service/impl/client/R00756Test.java
Dima can you provide link for related ticket and small description for this merge request 
Thanks
=> PROF-31: rule R-00756 is implemented

api-core-test-support/config/config.yml, api-core-test-support/src/main/java/gov/ca/cwds/rest/authenticate/CWDSAuthenticationClient.java, api-core-test-support/src/main/java/gov/ca/cwds/rest/authenticate/CWDSAuthenticationClientConfig.java
just cleaned up authenticate client classes.
=> INT-1445-Authentication class

api-core-test-support/src/main/java/gov/ca/cwds/test/support/BasePerryV2TokenProvider.java
Logs were added
- [CALS-5820 Upgrade integration tests in CALS API to support Perry v2](https://osi-cwds.atlassian.net/browse/CALS-5820)
Logging was added for convenient troubleshooting  
N/A
N/A
=> CALS-5820 Upgrade integration tests in CALS API to support Perry v2

legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/service/impl/ClientCoreService.java
- https://osi-cwds.atlassian.net/browse/CALS-5654
Added additional method to ClientCoreService to get Clients by FacilityId
=> CALS-5654: Added additional method to ClientCoreService to get Clients by FacilityId

legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/Constants.java, legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/dto/PlacementHomeEntityAwareDTO.java, legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/service/impl/OtherClientNameService.java, legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/service/impl/PlacementHomeCoreService.java
- [PROF-40: Other Client Name phonetic search](https://osi-cwds.atlassian.net/browse/PROF-40)
Client Name Phonetic is persisted for each new other client name created
The other client name has been introduced earlier, phonetic search persisting was a tech dept.
=> NEW:PROF-40 Phonetic search for other client name

legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/service/impl/OtherClientNameService.java
=> SSANAME3 dao used with correct sessionfactory

legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/Referral.java
Refactoring for Referral.findReferralsByClient named query @ Referral.java;
- [CALS-5755: Staff person for child placed in facility](https://osi-cwds.atlassian.net/browse/CALS-5755)
Refactoring for Referral.findReferralsByClient named query @ Referral.java;
N/A
N/A
Notes:
Jenkins build is successful for those changes: http://jenkins.dev.cwds.io:8080/job/tpt-api-core/573/
=> CALS-5755 CALS API: Staff person for child placed in facility

api-core-cms/src/main/java/gov/ca/cwds/data/persistence/cms/CmsKeyIdGenerator.java, api-core-cms/src/test/java/gov/ca/cwds/data/persistence/cms/CmsKeyIdGeneratorTest.java, legacy-data-access-services/src/main/resources/client-relationship-legacy-rules/R-00753.drl
- Add Key decomposer (from key to date)
- refactoring of drool file
- https://osi-cwds.atlassian.net/browse/RL-23
implement of service for decompose date from key id
=> RL-23 (Implement R-08840 rule for Client Relationship Update)

legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/Constants.java, legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/dto/ClientEntityAwareDTO.java, legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/service/impl/ClientCoreService.java, legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/service/impl/OtherClientNameService.java, legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/service/impl/SubstituteCareProviderCoreService.java, legacy-data-access-services/src/main/resources/client-legacy-rules/R-10841.drl, legacy-data-access-services/src/main/resources/client-legacy-rules/auto-discovery, legacy-data-access-services/src/test/java/gov/ca/cwds/cms/data/access/service/impl/client/ClientTestUtil.java, legacy-data-access-services/src/test/java/gov/ca/cwds/cms/data/access/service/impl/client/R05786Test.java, legacy-data-access-services/src/test/java/gov/ca/cwds/cms/data/access/service/impl/client/R10841Test.java
- [PROF-30: Implement R-10841 BE rule for Client Update](https://osi-cwds.atlassian.net/browse/PROF-30)
=> NEW:PROF-30 Implement R-10841 BE rule for Client Update

legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/Constants.java
=> minor fix PROF-30

api-core-abac/src/main/java/gov/ca/cwds/authorizer/drools/configuration/DroolsAuthorizer.java, api-core-cms/src/main/java/gov/ca/cwds/data/ApiResultSetHandler.java, drools-engine/src/main/java/gov/ca/cwds/drools/validation/ValidationConfigurationRegistry.java, legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/CWSIdentifier.java, legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/builder/EntityAwareDTOBuilder.java, legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/dto/PlacementHomeEntityAwareDTO.java, legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/dto/SCPEntityAwareDTO.java, legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/mapper/CountyOwnershipMapper.java, legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/mapper/ExternalInterfaceMapper.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/Client.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/ClientRelationship.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/ClientUc.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/DasHistory.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/HealthReferral.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/SchoolOriginHistory.java
=> SONAR FIXES

legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/CmsPersistentObject.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/CmsPersistentObjectBase.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/CmsPersistentObjectVersioned.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/dao/CountryDao.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/BaseLicensingVisit.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/BasePlacementEpisode.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/BaseStaffPerson.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/Case.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/Client.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/HealthReferral.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/HealthScreening.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/LongText.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/ParentalRightsTermination.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/converter/NullableBooleanConverter.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/enums/BaseEntityEnumConverter.java, legacy-data-access/src/test/java/gov/ca/cwds/data/legacy/cms/dao/CaseDaoTest.java
=> D Palczewski sonar issues fix

build.gradle, legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/service/impl/ChildClientCoreService.java, legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/service/impl/ClientCoreService.java, legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/service/impl/CsecHistoryService.java, legacy-data-access-services/src/test/java/gov/ca/cwds/cms/data/access/service/impl/dbDependent/CsecHistoryServiceTest.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/CsecHistory.java
- [PROF-66: CSEC HISTORY entity and update fix](https://osi-cwds.atlassian.net/browse/PROF-66)
=> PROF-66: CSEC HISTORY entity and update fix

build.gradle, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/Client.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/enums/Gender.java, legacy-data-access/src/test/java/gov/ca/cwds/data/legacy/cms/dao/ClientDaoTest.java, legacy-data-access/src/test/resources/dbunit/CaseActiveCanceled.xml, legacy-data-access/src/test/resources/dbunit/Client/find/Clients.xml, legacy-data-access/src/test/resources/dbunit/Client/insert/Client_after_insert.xml, legacy-data-access/src/test/resources/dbunit/Client/update/Client_after_update.xml, legacy-data-access/src/test/resources/dbunit/Client/update/Client_before_update.xml, legacy-data-access/src/test/resources/dbunit/Client/update/FCEligibility.xml, legacy-data-access/src/test/resources/dbunit/OptimisticLocking.xml
- [PROF-55: CWS/CMS 8.2 support](https://osi-cwds.atlassian.net/browse/PROF-55)
CWS/CMS 8.2 support - new fields for Client, new gender type
=> Prof 55 CWS/CMS 8.2 support

.github/PULL_REQUEST_TEMPLATE.md, Jenkinsfile-complete.groovy, Jenkinsfile-pull-request.groovy, build.gradle
Jenkins pipeline refactoring to split pull request pipeline and complete release pipeline. Sonar exclusion added for Swagger static resources.
=> Jenkins pipeline refactoring. Sonar exclusion added for Swagger static resources.

api-core-cms/src/main/java/gov/ca/cwds/data/es/ElasticSearchPerson.java
- [INT-1711:Add Middle Names and Suffixes to Elastic Search](https://osi-cwds.atlassian.net/browse/INT-1711)
Add Middle Names and Suffixes to Elastic Search
Additional information is available in 
- [INT-1665:SPIKE: Implications for search enhancements](https://osi-cwds.atlassian.net/browse)
N/A
N/A
=> INT-1711 Add Middle Names and Suffixes to Elastic Search

legacy-data-access/src/main/java/gov/ca/cwds/data/BaseDaoImpl.java, legacy-data-access/src/main/java/gov/ca/cwds/data/CrudsDaoImpl.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/CmsPersistentObjectVersioned.java
- [INT-1592: XA transactions](https://osi-cwds.atlassian.net/browse/INT-1592)
CrudDaoImpl checks whether a session is open or opens a new one.
N/A
N/A
=> Dave int 1592

api-core-cms/src/main/java/gov/ca/cwds/data/es/ElasticsearchDao.java
-https://osi-cwds.atlassian.net/browse/INT-1723
Neutron to create Elasticsearch Alias for people-summary index
- [x ] I have NOT included tests 
N/A
N/A
=> INT-1723 Neutron to create Elasticsearch Alias for people-summary index

Jenkinsfile-complete.groovy, Jenkinsfile-pull-request.groovy, build.gradle
JaCoCo report combined in one file to improve cross-module coverage
N/A
N/A
=> JaCoCo report combined in one file to improve cross-module coverage

api-core-cms/src/main/java/gov/ca/cwds/rest/api/domain/cms/SystemCodeCache.java, legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/service/impl/ClientRelationshipCoreService.java, legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/service/lifecycle/DataAccessServiceLifecycle.java, legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/service/lifecycle/DefaultDataAccessLifeCycle.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/dao/TribalMembershipVerificationDao.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/facade/CaseByStaff.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/facade/ReferralByStaff.java
=> Dave javadoc

api-core-cms/src/main/java/gov/ca/cwds/rest/api/domain/cms/LegacyTable.java
- [HOT-1885: Elasticsearch: last known residence address (R-02294)](https://osi-cwds.atlassian.net/browse/HOT-1885)
Add missing tables to enum LegacyTable.
Added new entries to an enum.
N/A
N/A
=> Dave hot 1885

api-core-cms/src/main/java/gov/ca/cwds/common/NameSuffixTranslator.java, api-core-cms/src/main/java/gov/ca/cwds/data/es/ElasticSearchPerson.java, api-core-cms/src/test/java/gov/ca/cwds/common/NameSuffixTranslatorTest.java, api-core-common/src/main/java/gov/ca/cwds/utils/RomanNumerals.java, api-core-common/src/test/java/gov/ca/cwds/utils/RomanNumeralsTest.java
https://osi-cwds.atlassian.net/browse/HOT-1895
Common functionality for name suffix translations. This will be used by Neutron and Ferb to translate client name suffixes in a uniform manner.
N/A
N/A
=> Common functionality for name suffix translations

build.gradle, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/syscodes/IndianTribeType.java
new version of data model
N/A
N/A
=> new version of data model

api-core-test-support/src/main/java/gov/ca/cwds/test/support/BasePerryV2TokenProvider.java, api-core-test-support/src/main/java/gov/ca/cwds/test/support/PerryV2DevModeTokenProvider.java
Fix integration tests support: token provider uses callback url instead of "/"
N/A
N/A
=> Fix integration tests support: token provider uses localhost callback url instead of "/"

api-core-cms/src/main/java/gov/ca/cwds/rest/services/cms/CachingSystemCodeService.java
https://osi-cwds.atlassian.net/browse/SNAP-78
=> Add a check to avoid the "0" SystemCode

legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/BasePlacementHome.java
- [SEAR-151: Slow access to Profile Page when pulling Facility Information](https://osi-cwds.atlassian.net/browse/SEAR-151)
The PlacementHome Entity was refactored
N/A
N/A
=> SEAR-151 Entity refactoring

build.gradle
=> Datamodel update

legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/BasePlacementEpisode.java
https://osi-cwds.atlassian.net/browse/SEAR-153
Fixed one of performance bottlenecks. Getting rid of database queries when calculating hashCode
N/A
N/A
=> SEAR-153  Slow access to Profile Page when pulling Children Information

api-core-cms/src/main/java/gov/ca/cwds/data/cms/SystemCodeDao.java, api-core-cms/src/main/java/gov/ca/cwds/rest/api/domain/cms/SystemCodeCache.java
https://osi-cwds.atlassian.net/browse/HOT-1973
SystemCodeCache. getSystemCodeId interface method parameter has changed as per the implementation, and SystemCodeDao changed to get open session as per the other methods to fix the 
"No session currently bound to an execution context"
=> Changed the method parameter as per Implementation

api-core-cms/src/main/java/gov/ca/cwds/data/persistence/cms/BaseOtherAdultInPlacemtHome.java, api-core-cms/src/main/java/gov/ca/cwds/data/persistence/cms/BaseOtherChildInPlacemtHome.java
https://osi-cwds.atlassian.net/browse/HOT-2030
Attempt to extract first and last names from name field.
N/A
N/A
=> HOT-2030 Resolve bug in Other Adult/Child in home

api-core-abac/src/main/java/gov/ca/cwds/data/dao/cms/CountyDeterminationDao.java, api-core-abac/src/test/java/gov/ca/cwds/service/ClientCountyDeterminationServiceTest.java
N/A
Made the "managed" property optional for injections. No need to change APIs and provide redundant property binding for a new version of the api-core.
Just refactoring no new functionality
N/A
N/A
=> Made "managed" property optional

legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/dao/NonCWSNumberDao.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/NonCWSNumber.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/SafelySurrenderedBabies.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/SpecialProjectReferral.java, legacy-data-access/src/test/java/gov/ca/cwds/data/legacy/cms/dao/NonCWSNumberDaoTest.java
Added DAO for Non-CWS Client Identifiers
N/A
N/A
=> Added DAO for Non-CWS Client Identifiers

legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/SpecialProject.java
Added quotes around a sql where clause text value.
N/A
N/A
=> Fixed a query for special projects

api-core-cms/src/main/java/gov/ca/cwds/data/es/ElasticSearchPerson.java, api-core-cms/src/main/java/gov/ca/cwds/data/persistence/cms/BaseClient.java, api-core-cms/src/main/java/gov/ca/cwds/data/std/ApiPersonAware.java, api-core-cms/src/main/resources/elasticsearch/mapping/map_person_summary.json
https://osi-cwds.atlassian.net/browse/HOT-2029
Added person date of death
No unit tests needed.
N/A
N/A
=> Added person date of death

legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/SafelySurrenderedBabies.java
=> Fixed SSB date datatype issue

legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/NonCWSNumber.java
Added missing primary key annotation
N/A
N/A
=> Added missing primary key annotation

legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/NonCWSNumber.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/SafelySurrenderedBabies.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/SpecialProject.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/SpecialProjectReferral.java
Added few column constraints
N/A
N/A
=> Added few column constraints

legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/SafelySurrenderedBabies.java
Fixed Y/N (boolean) column type
N/A
N/A
=> Fixed Y/N (boolean) column type

legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/service/ClientRelationshipService.java, legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/service/impl/clientrelationship/ClientRelationshipCoreService.java, legacy-data-access-services/src/test/java/gov/ca/cwds/cms/data/access/service/impl/clientrelationship/ClientRelationshipCoreServiceTest.java
https://osi-cwds.atlassian.net/browse/HOT-1986
The Id needs to be returned after saving to DB. The return type of the save was changed to return the saved object
N/A
N/A
=> HOT-1986 change relationship save to return saved object

api-core-common/src/main/java/gov/ca/cwds/rest/api/domain/DomainChef.java, api-core-common/src/test/java/gov/ca/cwds/rest/api/domain/DomainChefTest.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/dao/SpecialProjectDao.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/dao/SpecialProjectReferralDao.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/SpecialProject.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/SpecialProjectReferral.java, legacy-data-access/src/test/java/gov/ca/cwds/data/legacy/cms/dao/SpecialProjectDaoTest.java, legacy-data-access/src/test/resources/dbunit/SpecialProjects.xml
HOT-1959 Save CSEC screening data to CWS/CMS  https://osi-cwds.atlassian.net/browse/HOT-1959### Technical Description
Modified so that classes can be used for SSB and CSEC special projects
Add cookLocalDate() and uncookLocalDateString() to DomainChef.java
Unit test are included in API
N/A
N/A
=> HOT-1959: modified for Special Project refactor

legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/dao/SafetyAlertActivationReasonTypeDao.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/syscodes/SafetyAlertActivationReasonType.java
https://osi-cwds.atlassian.net/browse/HOT-2056
Safety Alert Entity has SafetyAlertActivationReasonType class and has to pull the System Code based on the type, So created a Dao and added a named query to pull the SystemCode based on the reason Type.
=> Added a Dao and Named query to pull the Activation reason type from SytemCode Table

api-core-cms/src/main/java/gov/ca/cwds/rest/services/cms/CachingSystemCodeService.java, api-core-cms/src/test/java/gov/ca/cwds/rest/services/cms/CachingSystemCodeServiceTest.java
https://osi-cwds.atlassian.net/browse/HOT-2053
N/A
N/A
=> System code cache service logging

api-core-cms/src/main/java/gov/ca/cwds/data/cms/SystemCodeDao.java, api-core-cms/src/main/java/gov/ca/cwds/data/cms/SystemMetaDao.java
https://osi-cwds.atlassian.net/browse/HOT-2053
Grab hibernate session correctly for system codes
N/A
N/A
=> Grab hibernate session correctly for system codes

api-core-cms/src/main/java/gov/ca/cwds/data/es/ElasticSearchPerson.java, api-core-cms/src/main/resources/elasticsearch/mapping/map_person_summary.json
https://osi-cwds.atlassian.net/browse/HOT-2073
N/A
N/A
=> Added open case responsible agency code.

api-core-rest/src/main/java/gov/ca/cwds/logging/LoggingContext.java
https://osi-cwds.atlassian.net/browse/SNAP-284
Added additional logging fields
N/A
N/A
=> Added additional logging fields

api-core-cms/src/main/java/gov/ca/cwds/rest/api/domain/cms/SystemCodeCache.java, api-core-cms/src/main/java/gov/ca/cwds/rest/services/cms/CachingSystemCodeService.java
Added cache size retrieval function
N/A
N/A
=> Added cache size retrieval function

api-core-cms/src/main/resources/elasticsearch/setting/people-summary-index-settings.json
https://osi-cwds.atlassian.net/browse/SNAP-419
N/A
N/A
=> Updated ES Settings

legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/dao/PlacementHomeDao.java, legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/service/impl/clientrelationship/ClientRelationshipCoreService.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/dao/ActiveServiceComponentTypeDao.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/dao/ApprovalStatusTypeDao.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/dao/CaseClosureReasonTypeDao.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/dao/ClientAddressDao.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/dao/ClientDao.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/dao/CountiesDao.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/dao/CountryDao.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/dao/CreditReportHistoryDao.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/dao/CsecHistoryDao.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/dao/DasHistoryDao.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/dao/DeathCircumstancesTypeDao.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/dao/DeliveredServiceDao.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/dao/FCEligibilityDao.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/dao/FacilityTypeDao.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/dao/LicenseStatusDao.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/dao/MedicalEligibilityApplicationDao.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/dao/NearFatalityDao.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/dao/SchoolOriginHistoryDao.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/dao/SpecialEducationDao.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/dao/StateDao.java, legacy-data-access/src/main/java/gov/ca/cwds/data/stream/AbstractResultsStreamer.java
No Jira
Refactored the dao's to grabSession() instead of getSessionFactory().getCurrentSession()
N/A
N/A
=> Refactored the dao's to grabSession()

api-core-abac/src/main/java/gov/ca/cwds/authorizer/AbstractBaseAuthorizer.java
- https://osi-cwds.atlassian.net/browse/SEAR-355
New lines Replaced in ABAC logging to improve log shape
N/A
N/A
=> SEAR-355: replace new lines in ABAC logging

legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/LicensingIssue.java
https://osi-cwds.atlassian.net/browse/SEAR-30
Added new attribute issueNotes to LicensingIssue entity
=> SEAR-30 added issueNotes to LicensingIssue entity

api-core-rest/src/main/java/gov/ca/cwds/dto/app/HealthCheckResultDto.java, api-core-rest/src/main/java/gov/ca/cwds/dto/app/SystemInformationDto.java, api-core-rest/src/main/java/gov/ca/cwds/rest/resources/system/AbstractSystemInformationResource.java, api-core-rest/src/test/java/gov/ca/cwds/dto/app/HealthCheckResultDtoTest.java, api-core-rest/src/test/java/gov/ca/cwds/rest/resources/system/AbstractSystemInformationResourceTest.java, api-core-rest/src/test/java/gov/ca/cwds/rest/resources/system/TestSystemInformationResource.java
- [CANS-429: Update cals-api to use system-information json format](https://osi-cwds.atlassian.net/browse/CANS-429)
Added abstract class for building RESTful SystemInformationResource classes in CARES Applications.
=> CANS-429: Update cals-api to use system-information json format

api-core-rest/src/main/java/gov/ca/cwds/rest/resources/system/AbstractSystemInformationResource.java, api-core-rest/src/test/java/gov/ca/cwds/rest/resources/system/TestSystemInformationResource.java
- improvement to AbstractSystemInformationResource
https://osi-cwds.atlassian.net/browse/CANS-430
=> CANS-430: Update dora-api to use system-information json format

legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/StaffPerson.java
Fix for [CANS-607](https://osi-cwds.atlassian.net/browse/CANS-607)
Remove null values when searching for client ids by staff id
N/A
N/A
=> Remove null values when searching for client ids by staff id

legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/dao/ReferralDao.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/Referral.java, legacy-data-access/src/test/java/gov/ca/cwds/data/legacy/cms/dao/ReferralDaoTest.java
https://osi-cwds.atlassian.net/browse/CANS-663
Add PersonDao#findReferralIdsByClientIdAndActiveDate()
N/A
N/A
=> CANS-663. Referral/Case Refactored

api-core-cms/src/main/java/gov/ca/cwds/data/persistence/cms/CmsKeyIdGenerator.java, api-core-test-support/src/main/java/gov/ca/cwds/test/support/H2Function.java, legacy-data-access/build.gradle, legacy-data-access/src/test/java/gov/ca/cwds/data/legacy/cms/persistence/InMemoryTestResources.java
=> H2 timestamp alias moved to test support

legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/dao/ClientDao.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/Client.java
- https://osi-cwds.atlassian.net/browse/CANS-736
Fix for authorization issue in zOS
N/A
N/A
=> CANS-736: query parameter fix

api-core-cms/src/main/java/gov/ca/cwds/data/persistence/cms/CmsKeyIdGenerator.java, api-core-cms/src/test/java/gov/ca/cwds/data/persistence/cms/CmsKeyIdGeneratorTest.java
- https://osi-cwds.atlassian.net/browse/CANS-556
refactoring, tests
N/A
N/A
=> CANS-556 Create ETL app/program/job to convert UIID to Base62 

build.gradle, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/dao/ClientDao.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/Client.java, legacy-data-access/src/test/java/gov/ca/cwds/data/legacy/cms/dao/ClientDaoTest.java
- https://osi-cwds.atlassian.net/browse/CANS-736
Data access methods added to fined assignment data for supervisor subordinates
N/A
N/A
=> CANS-736: supervisor assignment authorization logic

api-core-test-support/src/main/java/gov/ca/cwds/test/support/TestPrincipalUtils.java, drools-engine/build.gradle, drools-engine/src/main/java/gov/ca/cwds/drools/DroolsKieContainerInstaller.java
=> CANS-682: Decision tables support

build.gradle
=> SEAR-475 upgraded version number

api-core-cms/src/main/java/gov/ca/cwds/data/es/ElasticSearchPerson.java, api-core-cms/src/test/java/gov/ca/cwds/data/es/ElasticSearchPersonTest.java
- [SNAP-816 Search Date of Birth in Different Date Formats](https://osi-cwds.atlassian.net/browse/SNAP-816)
Added requested DOB permutations/formats.
N/A
N/A
=> SNAP-816 Search Date of Birth in Different Date Formats

build.gradle, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/StaffPerson.java
- https://osi-cwds.atlassian.net/browse/CANS-943
N/A
N/A
=> CANS-943: Supervisor subordinate query fixed to not include end dated authorities

api-core-cms/src/main/java/gov/ca/cwds/data/es/ElasticSearchPerson.java, api-core-cms/src/test/java/gov/ca/cwds/data/es/ElasticSearchPersonTest.java
- [SNAP-846 DOB Search Format Includes Century](https://osi-cwds.atlassian.net/browse/SNAP-846)
Added two more formats for the DOB search that include century.
N/A
N/A
=> SNAP-846 DOB Search Format Includes Century

api-core-common/src/main/java/gov/ca/cwds/rest/exception/IssueDetails.java, api-core-rest/src/main/java/gov/ca/cwds/logging/AuditLogger.java, api-core-rest/src/main/java/gov/ca/cwds/rest/resources/SimpleResourceDelegate.java, api-core-rest/src/test/java/gov/ca/cwds/rest/resources/SimpleResourceDelegateTest.java, legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/dto/PlacementHomeEntityAwareDTO.java, legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/dto/SCPEntityAwareDTO.java, legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/inject/AbstractDataAccessServicesModule.java, legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/mapper/ClientMapper.java, legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/mapper/CountyOwnershipMapper.java, legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/mapper/ExternalInterfaceMapper.java, legacy-data-access-services/src/test/java/gov/ca/cwds/cms/data/access/service/impl/substituteCareProvider/R07045Test.java, legacy-data-access/src/main/java/gov/ca/cwds/data/CrudsDaoImpl.java, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/dao/ClientDao.java
- [CODE-149: Fix critical code smells for API core in Sonar Qube](https://osi-cwds.atlassian.net/browse/CODE-149)
All critical issues are fixed.
N/A
N/A
=> CODE-149 - Fix sonar critical code smells.

.codeclimate.yml, api-core-abac/src/main/java/gov/ca/cwds/authorizer/PlacementHomeCreateAuthorizer.java, api-core-abac/src/main/java/gov/ca/cwds/authorizer/PlacementHomeResultReadAuthorizer.java, api-core-abac/src/main/java/gov/ca/cwds/authorizer/SubstituteCareProviderCreateAuthorizer.java, api-core-abac/src/main/java/gov/ca/cwds/authorizer/util/StaffPrivilegeUtil.java, api-core-abac/src/main/java/gov/ca/cwds/service/ClientSensitivityDeterminationService.java, api-core-cms/src/main/java/gov/ca/cwds/data/SharedSessionFactory.java, api-core-cms/src/main/java/gov/ca/cwds/data/es/ElasticsearchDao.java, api-core-cms/src/main/java/gov/ca/cwds/data/persistence/EmbeddableCompositeKey2.java, api-core-cms/src/main/java/gov/ca/cwds/data/persistence/cms/BaseClient.java, api-core-cms/src/main/java/gov/ca/cwds/data/rules/TriggerTableException.java, api-core-cms/src/main/java/gov/ca/cwds/rest/services/cms/CachingSystemCodeService.java, api-core-cms/src/test/java/gov/ca/cwds/data/persistence/cms/CmsKeyIdGeneratorTest.java, api-core-cms/src/test/java/gov/ca/cwds/rest/api/persistence/cms/SystemMetaTest.java, api-core-rest/src/main/java/gov/ca/cwds/auth/ApiAuthenticationException.java, api-core-rest/src/main/java/gov/ca/cwds/auth/InvalidTokenException.java, api-core-rest/src/main/java/gov/ca/cwds/rest/shiro/YamlShiroBundle.java, api-core-test-support/src/main/java/gov/ca/cwds/test/support/BaseApiTest.java, api-core-test-support/src/main/java/gov/ca/cwds/test/support/BasePerryV2TokenProvider.java, api-core-test-support/src/main/java/gov/ca/cwds/test/support/JWTTokenProvider.java, api-core-test-support/src/main/java/gov/ca/cwds/test/support/LoggingFilter.java, api-core-test-support/src/main/java/gov/ca/cwds/test/support/RestClientTestRule.java, api-core-test-support/src/main/java/gov/ca/cwds/test/support/TestPrincipalUtils.java, legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/service/impl/PlacementHomeCoreService.java, legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/service/impl/tribalmembership/CreateLifeCycle.java, legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/service/impl/tribalmembership/CreateUpdateLifeCycle.java, legacy-data-access-services/src/main/java/gov/ca/cwds/cms/data/access/service/impl/tribalmembership/UpdateLifeCycle.java, legacy-data-access/src/main/java/gov/ca/cwds/data/CrudsDaoImpl.java
- [FIT-454: Name of Story](https://osi-cwds.atlassian.net/browse/FIT-454)
N/A
N/A
=> WIP: FIT-454 - Fix sonar major code smells.

Jenkinsfile-complete.groovy, Jenkinsfile-pull-request.groovy
- https://osi-cwds.atlassian.net/browse/FIT-404
Project is using the single shared library created
This is a Jenkins config only so no tests.
N/A
N/A
=> Fit 404 apply code quality shared library

Jenkinsfile-complete.groovy, Jenkinsfile-pull-request.groovy
- https://osi-cwds.atlassian.net/browse/FIT-404
Add missing import of jenkins pipeline utils
N/A
N/A
=> import jenkins pipeline utils

api-core-cms/src/main/java/gov/ca/cwds/data/es/ElasticSearchPerson.java
- [SNAP-953 Search by Sex At Birth](https://osi-cwds.atlassian.net/browse/SNAP-953)
defaulting gender to "unknown"m so any other value except F/f,M/m,I/i will result to "unknown"
N/A
N/A
=> SNAP-953 Search by Sex At Birth

api-core-abac/build.gradle, build.gradle, legacy-data-access-services/build.gradle, legacy-data-access/build.gradle, legacy-data-access/src/main/java/gov/ca/cwds/data/legacy/cms/entity/BaseLicensingVisit.java
- [SEAR-636: Name of Story](https://osi-cwds.atlassian.net/browse/SEAR-636)
Removed LIC_VSTT.VISIT_NOTE column
=> SEAR-636 removed LIC_VSTT.VISIT_NOTE column

api-core-cms/src/main/java/gov/ca/cwds/data/persistence/XADataSourceFactory.java
=> SNAP-1093:FIX XA POOL CONNECTION REVERT

api-core-common/src/main/java/gov/ca/cwds/ObjectMapperUtils.java
https://osi-cwds.atlassian.net/browse/MDS-63
N/A
N/A
=> Removed redundant method calls.

README.md, api-core-abac/README.md, api-core-test-support/README.md, drools-engine/README.md, legacy-data-access-services/README.md, legacy-data-access/README.md
- https://osi-cwds.atlassian.net/browse/CANS-1255
N/A
N/A
=> CANS-1255: readme updates for API Core

api-core-es/api-core-es-interfaces/src/main/java/gov/ca/cwds/data/es/ElasticSearchPerson.java, api-core-es/api-core-es-interfaces/src/test/java/gov/ca/cwds/data/es/ElasticSearchPersonTest.java
- [CMO-280: Name of Story](https://osi-cwds.atlassian.net/browse/CMO-280)
Migrate Neutron Elasticsearch fields to shared code.
N/A
N/A
=> CMO-280: Neutron fields
